services:

  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgresql://conectando_patas_db_user:2lWME2bjFHArDP2vigJ5R7CItt0zmVzh@dpg-db4em060tbcc73e4k1f0-a/conectando_patas_db
    depends_on:
      - db

  db:
    image: postgres:17

    environment:
      POSTGRES_DB: conectando_patas_db
      POSTGRES_USER: conectando_patas_db_user
      POSTGRES_PASSWORD: 2lWME2bjFHArDP2vigJ5R7CItt0zmVzh

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data-base/banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:

  postgres_data: